//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestaV2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioRespuestas
    {
        public int IdUsuarioRespuestas { get; set; }
        public int IdPregunta { get; set; }
        public int IdPreguntaRespuesta { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdEncuesta { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public Nullable<int> IdFechaEncuesta { get; set; }
    
        public virtual EncuestaTipo EncuestaTipo { get; set; }
        public virtual FechaEncuesta FechaEncuesta { get; set; }
        public virtual PreguntaRespuestas PreguntaRespuestas { get; set; }
        public virtual Preguntas Preguntas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
